export const languages=[
    {
        value:'0',
        label:'Hindi'
    },
    {
        value:'1',
        label:'English'
    },
    {
        value:'2',
        label:'German'
    },
    {
        value:'3',
        label:'French'
    },
    {
        value:'4',
        label:'Spanish'
    },
    {
        value:'5',
        label:'Bahasa'
    },
    {
        value:'6',
        label:'Dutch'
    },
    {
        value:'7',
        label:'Tamil'
    },
    {
        value:'8',
        label:'Portuguese'
    }
];